### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sla-te** [hhu-propra2/abschlussprojekt-makeitlookeasy#10]

**Comment by sla-te** [comment]
giovanni is working on it at the moment.. see write-up issue

**Comment by gcascio** [comment]
New structure required, so images of the documentation have a place to live:
Maybe:

- Docu
    - documentation.md
    - image01.png

**Comment by sla-te** [comment]
Folder structure created, the whole documentation now lives in its new own home at ./documentation 

Auszug aus jans write-up zu den Dingen, die noch in die Doku müssen:

* Angaben zur Verfügbarkeit (Detailsansicht)  
* Kunde kann jederzeit den Artikel zurückgeben (Dokumentation)
* Gibt ein Kunde den Artikel nicht rechtzeitig zurück, wird der Verfügbarkeitszeitraum nicht automatisch aktualisiert.

**Comment by sla-te** [comment]
* admin login for conflicts
* hans base user with many cases

**Comment by sla-te** [comment]
* empfaenger vom emailsender
