### ISSUE TITLE
Keep raising sonarqubes code quality level

### ISSUE THREAD

**Issue by sla-te** [hhu-propra2/abschlussprojekt-makeitlookeasy#12]

**Comment by sla-te** [comment]
falls bock vorhanden ist.. müssen wir ja nicht machen

**Comment by jwiebels** [comment]
Removed bugs and critical errors (E -> A).
Vulnerabilites (E) and Code Smells (A) still open.

**Comment by sla-te** [comment]
nur 0,5% zum quality gate^^ https://sonarcloud.io/dashboard?id=de.propra2%3Aausleiherino24
