### ISSUE TITLE
show avilability / calender

### ISSUE THREAD

**Issue by sla-te** [hhu-propra2/abschlussprojekt-makeitlookeasy#16]

**Comment by sla-te** [comment]
da gibts ne gute vorlage auf share4good.de

**Comment by sla-te** [comment]
machen wir den noch, oder nicht?

**Comment by jopep100** [comment]
Ja, versuchen wir.

**Comment by sla-te** [comment]
@jopep100  kalender ist jetzt da und funktioniert. gibt nur das problem, dass man ohne weiteres keinen artikel buchen kann.

man muss erst darauf kommen, dass man manuell das enddatum zwei tage nach vorne setzt um dann das startdatum auf den nächsten tag setzen zu können. erst dann kann man einen artikel buchen, anderenfalls erscheint jedes mal die fehlermeldung.

**Comment by jopep100** [comment]
Ich weiß, dass der Kalendar da ist. Ich hab ihn ja gemacht 😄 

Guck ich morgen nach.

**Comment by sla-te** [comment]
tested and working
