### ISSUE TITLE
fix failing tests in master (7)

### ISSUE THREAD

**Issue by sla-te** [hhu-propra2/abschlussprojekt-makeitlookeasy#27]

**Comment by sla-te** [comment]
was ist denn hier bis jetzt passiert?

**Comment by sla-te** [comment]
@jopep100 dürfen die anderen auf erfahren, warum du dich hieran nicht beteiligen möchtest?

**Comment by jopep100** [comment]
Weil es noch genug andere Dinge im frontEnd gibt die ich erledigen muss.

**Comment by sla-te** [comment]
tests laufen durch, mache hier zu
