### ISSUE TITLE
Completing the JavaDocs

### ISSUE THREAD

**Issue by sla-te** [hhu-propra2/abschlussprojekt-makeitlookeasy#9]

**Comment by sla-te** [comment]
Solte ja jetzt alles klar sein, was noch fehlt

**Comment by MarkoWys** [comment]
JavaDocs sind für alle Services jetzt vollständig

**Comment by sla-te** [comment]
chat-,  und usercontroller fehlen noch welche, wenn ich das richtig sehe

**Comment by sla-te** [comment]
die sind jetzt vollständig.
